### ISSUE TITLE
Incompatible with gherkin 4.5.1?

### ISSUE THREAD

**Issue by Sut3kh** [jhedstrom/DrupalDriver#138]
When upgrading to gherkin 4.5.1 if I run tests via paths (i.e. `behat features/my.feature`) then i get errors like:

> [Behat\Testwork\Tester\Exception\WrongPathsException]                                                                               
  No specifications found at path(s) `features/my.feature`. This might be because of incorrect paths configuration in your `suites`.  

I'm not sure what has changed in gherkin but when it tries to validate the path the pwd is `DRUPAL_ROOT` and it fails (it is comparing `features/my.feature` to `web/features`).  If i comment out the following line in Drupal/Driver/Cores/Drupal8.php:30 '`chdir(DRUPAL_ROOT);`' then it works (but on an empty cache you get all sorts of weird issues when not in `DRUPAL_ROOT`).

The problem goes away if I force a downgrade via the following versions in composer:

```
"behat/behat": ">=3.1 <3.4",
"behat/gherkin": ">=4.4 <4.5",
```

Directory structure (using drupal-composer):

```
features/...
web/...
vendor/...
behat.yml
...
```

Major component versions when failing:
- drupal/core: 8.3.7
- drupal/drupal-extension: v3.3.1
- drupal/drupal-driver: v1.2.1
- behat/behat: *v3.4.1*
- behat/gherkin: *v4.5.1*

Major component versions when working:
- drupal/core: 8.3.7
- drupal/drupal-extension: v3.3.1
- drupal/drupal-driver: v1.2.1
- behat/behat: *v3.3.1*
- behat/gherkin: *v4.4.5*

**Comment by danepowell** [comment]
I think the problem you are facing is not due to Gherkin, but Behat (behat/behat). Specifically this change that appeared in 3.4 requires that you run Behat in the directory that you want to be the base path, rather than passing the path as an argument: https://github.com/Behat/Behat/commit/08802b7f2d736b88df339e5411a1c722e92adbe3

Seems like a bug to me, but I haven't had time to dig in.

**Comment by danepowell** [comment]
@jhedstrom this can probably be closed in favor of the upstream bug I linked above

**Comment by pfrenssen** [comment]
@danepowell Thanks for interlinking the issues, I was not aware that this was also reported here.

For people landing here, there are instructions on both of the upstream tickets explaining how to patch your installation.

A fix for this has been posted around the time this issue was created but unfortunately it is still not committed upstream. Feel free to vote for the upstream issue to help get maintainer attention, or even better to review + approve the PR.
